version: '3.3'

services:
    php:
        networks:
            - backend
        image: php:latest
        volumes:
            - ./public_html/:/var/www/html/
        deploy:
            replicas: 2
            update_config:
                parallelism: 1
                delay: 10s
    apache:
        networks:
            - frontend
            - backend
        image: httpd:latest
        volumes:
            - ./public_html/:/var/www/html/
        depends_on:
            - php
            - mysql
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
        ports: 
            - "8080:80"
    mysql:
        networks:
            - frontend
        image: mysql:latest
        environment:
            MYSQL_DATABASE: docker_database
            MYSQL_ROOT_PASSWORD: pswd
        deploy:
            replicas: 2
            update_config:
                parallelism: 2
                delay: 10s
            placement:
                constraints: [node.role == manager]
    phpmyadmin:
        networks:
            - frontend
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: pswd
        links:
            - mysql
        depends_on:
            - mysql
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
        ports:
            - '8000:80'
networks:
    frontend:
    backend: